### ISSUE TITLE
Fixed Columns and Issue with Table Tools

### ISSUE THREAD

**Issue by sumit91** [DataTables/FixedColumns#1]
Hi,

    I have having my first column as Fixed and I am using Table Tools feature provided. When i try printing the information All the columns are visiblle Except Fixed column. Any ideas on that ??

**Comment by DataTables** [comment]
This has been resolved with FixedColumns 3 which no longer uses the column visibility options to hide the columns that are fixed. Instead the fixed columns are overlaid on the table.
