### ISSUE TITLE
FixedColumns on hidden DataTable

### ISSUE THREAD

**Issue by dahrnsbrak** [DataTables/FixedColumns#22]
I'm using Bootstrap Tabs, and each tab has a DataTable with a FIxedColumn.  When I initialize both datatables (one visible, one hidden) both fixed columns are created and cause a mess. If it's too much trouble to add in functionality for FixedColumns on potentially hidden (then shown) DataTables, is there a way to remove the FixedColumn of a DataTable that is already initialized on the tab event?

Example of what I mean here:
http://jsfiddle.net/HEDvf/1353/

**Comment by DataTables** [comment]
There was a commit a little while back that added enable and disable abilities to FixedHeader ( https://github.com/DataTables/FixedHeader/commit/4eef3995bd39e2 ). Sorry I didn't update this bug at the time, it is int he FixedColumns repo so missed it.
