### ISSUE TITLE
paging should call _fnColCalc after new data is drawn

### ISSUE THREAD

**Issue by fleaflicker** [DataTables/FixedColumns#24]
The fixed column widths may have changed after paging. 

Currently, if the next page has wider fixed columns than the current page, a horizontal scroll bar appears just on the fixed columns.

I was able to fix this by calling _fnColCalc in _fnDraw, but this is wrong--it should only be called before _fnDraw but after a paging event.

**Comment by DataTables** [comment]
This has been done in fb1241ef4f1a82a60645c52b0ed9dc868336e83f and will be included in the next release.
