### ISSUE TITLE
Unwanted scrollbar on IE11 and offset on Chrome

### ISSUE THREAD

**Issue by Misiu** [DataTables/FixedColumns#25]
I'm trying to build sample table for my project, after some coding I've got this:
http://live.datatables.net/fojusec/6/edit
but I get unwanted behaviour on Chrome (36.0.1985.125 m) and on IE 11 on WIn8.1

![datatables_fixedcollumn](https://cloud.githubusercontent.com/assets/1741838/3765934/fde7625e-18bf-11e4-8936-add3e6d37017.JPG)

On IE11 (on right) You can see unwanted scroll bar (same happens when I remove all my custom css)
On Chrome (on left) after scrolling to bottom of table there is 1-2 pixels offset.

I'll build second sample with bootstrap 3, maybe this will help.

**Comment by DataTables** [comment]
Sorry for the massive delay on this one. Posting back now to say that this should be resolved with the latest software: http://live.datatables.net/licigeza/1/edit .
