### ISSUE TITLE
scrollbar is wider than x-scrollable area

### ISSUE THREAD

**Issue by croensch** [DataTables/FixedColumns#26]
The scrollbar stretches to the full table wide over the fixed left columns.
The scrollable area had ``left: ?px`` set in 1.9 before.

This code is missing from in _fnGridSetup in 1.10:
```javascript
this.dom.grid.dt.style.position = "absolute";
this.dom.grid.dt.style.top = "0px";
this.dom.grid.dt.style.left = this.s.iLeftWidth+"px";
this.dom.grid.dt.style.width = ($(this.dom.grid.dt).width()-this.s.iLeftWidth-this.s.iRightWidth)+"px";
```
Adding it did fix it.

**Comment by DataTables** [comment]
Sorry for the delay in looking into this. I've just loaded it up and it appears to work as expected with the latest software. The scrollbar does intentionally span the full width of the table - this was part of the FixedColumns 2.5 update which retooled it to work like that. It appears to be a love hate thing if people prefer it the way it now is or the way it was!
