### ISSUE TITLE
Fixed Columns breaks in IE9

### ISSUE THREAD

**Issue by arunsasi** [DataTables/FixedColumns#28]
I am trying in integrate fixed column in my application (Bootstrap based) . When i checked the live demo url the fixed first column height and scoll breaks. Please check the issue.

![demo](https://cloud.githubusercontent.com/assets/270789/4282705/364cfd20-3d5f-11e4-9d08-fdcafc83da8b.gif)

**Comment by DataTables** [comment]
This appears to have been fixed with the latest software. I'm going to be doing a release shortly.
