### ISSUE TITLE
tbody problem in ie8

### ISSUE THREAD

**Issue by psk11** [DataTables/FixedColumns#30]
Hello folks,

I am using the latest version of datatables and its working fine in the other browsers like chrome, IE9+ and others. But I am getting problem in ie8 and the problem is the table heads are appearing below table body. The below is sample code of js : 

 $(document).ready(function () {
        $('#tableData').DataTable({
            "ordering": false,
            "lengthMenu": [10, 50, 100],
            "saveState": true
        });
    }
    );

The tableData is the id of my table and I am using th for headers and td which should be sorted and filtered using datatables. 
What can be the issue with it?
![screen](https://cloud.githubusercontent.com/assets/7591609/4989257/c1192dbc-699b-11e4-8c66-0b8b35f6c2ce.png)

**Comment by DataTables** [comment]
Could you link to a page showing the issue please.

**Comment by psk11** [comment]
The project is on intranet of a private client so it is not possible to provide link of the page.

**Comment by psk11** [comment]
The other thing is that the tables is filled up with a row on run time and its also showing that 'No data available in table' along with the available data.

**Comment by DataTables** [comment]
Can you use http://live.datatables.net , JSFiddle, CodePen or something else to provide a test case that I can debug please.

**Comment by DataTables** [comment]
This is a screenshot of [my example page](http://datatables.net/extensions/fixedcolumns/examples/initialisation/simple.html) taken in IE8 (emulated) and it appears to work as expected.

![screen shot 2016-01-07 at 17 06 14](https://cloud.githubusercontent.com/assets/278219/12176800/0b860c14-b561-11e5-9f6a-1eb2eb571dea.png)

Going to close this issue for now until we have a working test case that will reproduce the issue.
