### ISSUE TITLE
Error when hiding columns with a column fixed on the right

### ISSUE THREAD

**Issue by rockshandy** [DataTables/FixedColumns#33]
I'm having a hard time track an issue when I try to make both a right and left column be fixed. When only fixing one left column, I can hide columns fine. As soon as I also fix one column on the right. I see the following at line 1115:

    Uncaught TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.

While tracing through a little, it seems to look at a column which doesn't have any table cells currently rendered, resulting in an undefined node.

Initializing fixed columns with:
```javascript
new $.fn.dataTable.FixedColumns(dtTable, {
  rightColumns: 1,
  leftColumns: 1
});
```

Any pointers?

**Comment by DataTables** [comment]
Can you link to a test case showing the issue please? Here is a test I just tried with a hidden column: http://live.datatables.net/morufabe/1/edit .

**Comment by rockshandy** [comment]
Well maybe I have something more complex going on, as adding a bit to the example doesn't seem to trigger the error I'm seeing in my app. I'll do some more debugging my side, thanks for the quick response.

**Comment by DataTables** [comment]
One thing to try, if you haven't already is to use the version of FixedColumns in this repo. There is a fix in there that possibly has the potential to cause this issue.

**Comment by rockshandy** [comment]
Oh that commit did fix my issue! Do you think there might be another release with that commit incoming? I'm using a few other plugins at a particular commit, so it's not a big deal.

**Comment by DataTables** [comment]
Ah good to hear!

Planning to do a release next week I hope.

If this is fixed I'll close this issue off now.
