### ISSUE TITLE
Colvis & Fixed columns(from the right side only).

### ISSUE THREAD

**Issue by omerman** [DataTables/FixedColumns#34]
It appears that if you have fixed columns from the right side, and you hide a column it causes some problems.
http://jsfiddle.net/bjsk18dt/3/

*Notice how after you hide columns, fixedColumns.js is throwing a script error.

**Comment by DataTables** [comment]
Hi,

This is already [fixed in the nightly](http://jsfiddle.net/bjsk18dt/4/). It was fixed in #33.
