### ISSUE TITLE
1st row getting sort icons as well as the header row

### ISSUE THREAD

**Issue by Jrizzi1** [DataTables/FixedColumns#37]
I have a table set up with <thead> and <tfoot>, with fixed columns 3.0.4, datatables 1.10.6, 
[datatables integration bootstrap](http://cdn.datatables.net/plug-ins/f2c75b7247b/integration/bootstrap/3/dataTables.bootstrap.js). bootstrap 3

When I include Fixedcolumns , it creates an extra sort icons on the first row in addition to the header having sort icons,

my code is like so, note i am using ajax to populate my results in a server side implementation

``` javascript
table = $('#example').DataTable( {
    scrollY: "600px",
    scrollX: "100%",
    scrollCollapse: true, 
    stateSave: false,
    serverSide: true,
    processing: true,
    ajax: {...}

  });
  new $.fn.dataTable.FixedColumns( table, {
        leftColumns: 2
    } );

```

![image](https://cloud.githubusercontent.com/assets/622313/7238326/77609834-e76f-11e4-8686-f65c6e1e8b61.png)

**Comment by DataTables** [comment]
The latest Bootstrap integration files will fix this.

**Comment by Jrizzi1** [comment]
thanks :)

**Comment by mojimi** [comment]
I still have this issue using the scroller plugin

**Comment by DataTables** [comment]
Happy to take a look at a test case showing the issue.

**Comment by mojimi** [comment]
@DataTables  Here it is : https://jsfiddle.net/1tyr0d4z/

In this fiddle I am showcasing several issues I had, first being the sorting icon on the first row.

Second being the fixedColumns, I'm not sure what is even happening.

Of course it could just be some bad configuration by my part, I just put together examples I found online.

**Comment by DataTables** [comment]
Thank you! it looks like this is a problem even with the latest nightly when using Bootstrap 4: http://live.datatables.net/qonebike/1/edit

**Comment by mojimi** [comment]
Would love to know if there's a workaround for this using css

I noticed the DTFC_RightWrapper, is using aria-hidden, which only hides an element on readers and such, adding

```
.DTFC_RightWrapper {
display : none
}
.dataTables_scrollBody thead {
visibility: hidden;
}
```

Solved two of the issues, except the ghost column scrolling behind

**Comment by DataTables** [comment]
Sorry - I included the wrong CSS file for my example above - I should have used `fixedColumns.bootstrap4.css` (not the DataTables one): http://live.datatables.net/qonebike/2/edit .

**Comment by mojimi** [comment]
@DataTables  Ah thanks, so is this something that was fixed in nightly or I used the wrong css?

**Comment by DataTables** [comment]
Its working in the nightly now. I think there is a bug in the current release of FixedColumns.

**Comment by mojimi** [comment]
@DataTables Thanks, but just a reminder, the original issue was the sorting icons in the first row using the Scroller plugin, in your latest example you didn't add the CDN for the Scroller plugin.

**Comment by DataTables** [comment]
Thanks! It seems that due to the CSS priorities it was only showing up with `table-sm` which I didn't have in my test case. [I've fixed the issue here](https://github.com/DataTables/DataTablesSrc/commit/a317c24bdd82238908138945bae7e168e6a7483f).
