### ISSUE TITLE
processing div being clipped

### ISSUE THREAD

**Issue by Jrizzi1** [DataTables/FixedColumns#38]
I have a server side table set up with fixed columns 3.0.4, datatables 1.10.6, 
datatables integration bootstrap 10.6. bootstrap 3

the "processing... " div is being clipped when using fixedcolumns, you can barely see the text 

![image](https://cloud.githubusercontent.com/assets/622313/7238627/b7652d44-e771-11e4-9f24-9a0cadc1cb7d.png)

sometimes this is more prominent than others based on how many results i am returning, (5 is clipped more than 10)

**Comment by DataTables** [comment]
Thanks for the picture. I'll try to sort this out later this week (hopefully tomorrow)

**Comment by DataTables** [comment]
I've just created an [example test case](http://live.datatables.net/voxebotu/1/edit) which appears to work just fine.

Can you link to a test case showing the issue please.

**Comment by Jrizzi1** [comment]
I'm working on creating a copy of the internal app I'm creating, the main difference i see so far between your example and my code is that I am calling ajax for a server-side implementation

**Comment by DataTables** [comment]
[This template](http://live.datatables.net/ssp-objects/1/edit) can be used to create a server-side processing test case.

**Comment by Jrizzi1** [comment]
it has todo with me including a dom specification

processing gets clipped in my environ and dissapears in live.datatables.net when i specify a dom like this :
```javascript
dom: "<'row'<'col-md-6 'l><'col-md-6 pull-right'>r>t<'row'<'col-md-6'i><'col-md-6'p>>",
```

[heres a client side example](http://live.datatables.net/voxebotu/2/edit)
[heres a serverside example](http://live.datatables.net/laxinabe/1/edit)

by commenting out that dom option, you can see processing reappear

**Comment by DataTables** [comment]
Move the `r` option after the `t` in the `dom` property: http://live.datatables.net/voxebotu/2/edit . Otherwise the table is on top of the processing element. The other option is to add a z-index` to the processing element.

**Comment by Jrizzi1** [comment]
sorry about bogging you down with that, sometimes the dom property gets confusing for me, your help is much appreciated
