### ISSUE TITLE
row on click event returns length of undefined error

### ISSUE THREAD

**Issue by Jrizzi1** [DataTables/FixedColumns#39]
I have an on click function storing the row data in a variable

if you click on the first two columns, you'll notice the function returns undefined, however any of the unfrozen columns returns the data object

I know that this has todo with the fact that the fixedcolumns are created in a cloned table, i was wondering if there was any workaround to this?

[here is my example](http://live.datatables.net/laxinabe/1/edit) , note the console log as you click the first two frozen columns versus any other column

**Comment by DataTables** [comment]
Sorry for the **long** delay on this one. The way to handle this is to use the [`fixedColumns().rowIndex()` method](http://datatables.net/reference/api/fixedColumns().rowIndex()) to lookup the row index for the row: http://live.datatables.net/laxinabe/37/edit
