### ISSUE TITLE
Best practice on adding inputs/filters to table headers when working with fixed columns?

### ISSUE THREAD

**Issue by vedmack** [DataTables/FixedColumns#40]
Hi,

I was wondering if there some recommended way to add inputs / filters to the table when using the fixed columns?

(somebody asked to add support to [yadcf](https://github.com/vedmack/yadcf) for FixedColumns)

Thanks

**Comment by DataTables** [comment]
To be honest, there isn't really a "recommended way". You would have to use jQuery / DOM manipulation to add the required elements to the cloned table components. I haven't yet come up with a good way of handling that in the API.

**Comment by vedmack** [comment]
and what is the way to get the info regarding the columns that are *fixed*? (using the fixedColumns api)

**Comment by DataTables** [comment]
No, sorry. The FixedColumns API doesn't really expose very much at all other than the ability to redraw.

Which brings up another issue you would face, when FixedColumns does a full redraw, it will clone the original elements again, and destroy the ones it has created previously. The result is that any end user input in the fixed elements will be lost.
