### ISSUE TITLE
Respecting rowspans in the fixed column

### ISSUE THREAD

**Issue by csweaver** [DataTables/FixedColumns#41]
I've got a table where the first column includes rows that have a rowspan > 1. When I try to use FixedColumns on this table the fixed column only uses the first column after the <tr> instead of respecting the multi row fields. 

Is there something I'm doing wrong, or is this feature not supported yet?

**Comment by DataTables** [comment]
Seems to work okay for me here: http://live.datatables.net/pataporu/1/edit . Can you link to a test case please.

**Comment by csweaver** [comment]
Thanks!

I've actually got my rowspan in the table body. Reading more it seems like this is not a supported feature (http://datatables.net/manual/tech-notes/4). I'll try to make an example case of my problem for you this afternoon.

**Comment by DataTables** [comment]
Ah - yes. In that case don't bother with a test case. As you note, rowspan / colspan in the `tbody` is not supported in DataTables and likely won't be for a long time to come due to the complexities that they would add.

I'll close this bug request as unsupported.
