### ISSUE TITLE
iLeftWidth isn't recalculated when underlying DT recalculates columns.

### ISSUE THREAD

**Issue by rgavrilov** [DataTables/FixedColumns#42]
I am using DT (1.10.3) with fixedColumns (3.0.5-dev)

I render table HTML using KO, and then initialize DT with `$(...).dataTables()` call.

Here is what I see during page load:

table is rendered
table is turned into a DT (with scrollX: true)
FC iLeftWidth is calculated (480px) (and matches first column width of the table, as expected)
DT's aoDrawCallback callback is fired which calls DT's _fnScrollDraw, which changes columns widths (first column gets reduced by 450px)
"draw.dt" event is raised
FC handles the event, and but only does `that._fnDraw.call( that, bFirstDraw );` without recalculating columns
As a result FC uses 480px for column width, and puts that over the column which is now 450px, not 480px

If I change FC's draw.dt handler to look like this (no claim it is a correct solution, I'm just demonstrating the problem) :

    .on( 'draw.dt.DTFC', function () {
        that._fnColCalc(); // <-- this causes iLeftWidth to get updated to match new DT's column geometry.
        that._fnDraw.call( that, bFirstDraw );
        bFirstDraw = false;
    } )

Then the problem goes away.

I think the problem maybe with DT's _fnScrollDraw function, that changes columns' widths but does not raise a notifications (e.g. "column-sizing.dt").

I tried upgrading to DT 1.10.7-dev, but that didn't help.

**Comment by DataTables** [comment]
Hi - thanks for posting this. Are you able to link to a test case showing the issue please?

**Comment by rgavrilov** [comment]
Sorry, I don't have a test case. I troubleshot and fixed it on a dev site.
If that would be of any help, I could show you the failure (with code) on
my screen (teamviewer or skype). skype: roman.gavrilov

**Comment by DataTables** [comment]
No worries. I'll need to find some time to create a test case so I can develop against it in that case. Due to current commitments I can't say when that will be I'm afraid.

**Comment by rgavrilov** [comment]
Understandable. My offer stands - if you need to demo the bug to you - I'm
available (UTC -6)

**Comment by Jrizzi1** [comment]
I may have come here to post about the same issue, [here is my demo](http://live.datatables.net/yuxorilo/1/edit?html,js,output)

if you sort on the first non-fixed column ( in this case Last Name), notice that descending order will cause both tables to become misaligned, creating an extra scrollbar for the fixed columns / overlaid clone columns, toggle the sort on that column and it will toggle the issue back and forth

**Comment by rsynnest** [comment]
Just wanted to say I also was experiencing this exact problem, thank you rgavrilov for the workaround!!

**Comment by Jrizzi1** [comment]
@rgavrilov your workaround also seems to fix the same issue i am experiencing, except that it does resize the column headers as well based on the column body length

**prior to sort**

![image](https://cloud.githubusercontent.com/assets/622313/7537980/c9d9241a-f56a-11e4-9b6b-7092de704e89.png)

**after sort**

![image](https://cloud.githubusercontent.com/assets/622313/7537966/b0e08368-f56a-11e4-9aae-6be7a183a3ac.png)

**Comment by DataTables** [comment]
Sorry for the delay in looking into this. I've committed the change in fb1241ef4f1a82a60645c52b0ed9dc868336e83f.
