### ISSUE TITLE
Misalignment when scrolled to the bottom

### ISSUE THREAD

**Issue by rgavrilov** [DataTables/FixedColumns#44]
I have a datatable configured with FixedColumns plugin and scrollY: 500px

When I scroll table (>600px high), the fixed column gets misaligned by 1px.

I traced it down to this FixedColumns rule:

    div.DTFC_LeftWrapper table.dataTable.no-footer,
    div.DTFC_RightWrapper table.dataTable.no-footer {
        border-bottom: none;
    }

my table is decorated with .table class which has
    
    border-bottom-width: 1px

as a result, main table is 667px, but cloned (left liner) is 666px, so liner falls short 1px when scrolled to the bottom.

**Comment by stanleyxu2005** [comment]
Is your problem related to mine? https://github.com/DataTables/FixedColumns/issues/72
