### ISSUE TITLE
3.0.5 release?

### ISSUE THREAD

**Issue by samccone** [DataTables/FixedColumns#46]
the 3.0.4 release has some pretty nasty memory leaks, that I traced down here https://github.com/twosigma/beaker-notebook/issues/1905#issuecomment-122926776

I fear that many people have this version in production without realizing that there is a large leak in play.

The fix that I put in place in our project, was to pull the commit in on fixed-columns master that had the memory leak fixes. 
https://github.com/twosigma/beaker-notebook/commit/b2fab524666beeafd01be034776c2a702fc8fb36

I would love to be able to not depend on a commit on the tree and instead just pull in 3.0.5. This would also ensure that people do not use the 3.0.4 release anymore.

Thanks for this great library :clap:

**Comment by DataTables** [comment]
I'm working one quite a number of updates at the moment, for simultaneous release. Unfortunately it is proving to be more involved than expected, but extracting myself from the hole I've dug to make the release without completing the work would probably delay everything quite a bit, and I'm already way behind where i want to be!

Long story short, I expect the release to be made before the end of the month.

**Comment by samccone** [comment]
@DataTables let me know if I can be of any help I appreciate the work you are doing :+1:

**Comment by DataTables** [comment]
Thanks :-). I'm in the middle of writing a download builder for all the new software atm, and then its just a case of documentation. Most software is ready to roll.
