### ISSUE TITLE
fixed columns working wrongly with rtl table

### ISSUE THREAD

**Issue by dineshrb** [DataTables/FixedColumns#48]
Below is the working fiddle of table with no direction specified:
https://jsfiddle.net/tp6xgu5o/1/

Below is the fiddle of table with direction rtl specified:
https://jsfiddle.net/tp6xgu5o/

**Comment by DataTables** [comment]
Thank you for posting this. I'm not sure what the correct solution would be here. Given that rtl will automatically relayout the table, reversing the column positions, should `leftColumns` still be the parameter that is used and FixedColumns should automatically reverse it as well?

**Comment by dineshrb** [comment]
Expected behaviour is the right column "first name"(as per rtl) should have been fixed and remaining items can be scrolled. By default, leftcolumns value is 1 i guess. So, it is initialised to 0. 

Note:
Without fixed columns, if i use scrollx: true with rtl itself, the relayout doesn't happen. Without scrollx, fixedcolumns won't work.

**Comment by DataTables** [comment]
You are correct the left column is fixed by default. Perhaps my naming choice should be changed to be `firstColumns` and `lastColumns`, although I can see that might be confusing as well.

My point is that if you initialise FixedColumns with `fixedColumns: true`, the first column should be fixed automatically - i.e. the first name column in this case. It seems that using different initialisation code for rtl is a bit of a pain.

**Comment by dineshrb** [comment]
In case of rtl, "first name" is not the first column. It is the last column.This can be seen without any datatable initialization.  
Below is the fiddle:
https://jsfiddle.net/tp6xgu5o/2/

Thats why i specified it as rightcolumns: 1. My point is that the "first name" should be fixed at the right and not on the left. Even, if i give fixedColumns: true, it is not working. Can you please provide the correct initialization code for rtl with "first name" column fixed at the right?

**Comment by DataTables** [comment]
> In case of rtl, "first name" is not the first column.

But surely it is the first column if you are reading right to left?

**Comment by dineshrb** [comment]
Yes you are right. But, the table itself is completely collapsed with your above said initialization.
Below is the fiddle:
https://jsfiddle.net/tp6xgu5o/3/

**Comment by DataTables** [comment]
Yes, that is a bug. Thanks for confirming what the bug is - that needs to be fixed. I just wanted to make sure that I fix the right then when I get a chance to do so.

**Comment by dineshrb** [comment]
Thanks!
