### ISSUE TITLE
without scrollY set, it may cause a unexpected gap right

### ISSUE THREAD

**Issue by yeahe83** [DataTables/FixedColumns#51]
Q1: without scrollY set, it may cause a unexpected gap right 

http://datatables.net/extensions/fixedcolumns/examples/initialisation/right_column.html,
and just uncomment the scrollY

```
$(document).ready(function() {
	var table = $('#example').DataTable( {
//		scrollY:        "300px",
		scrollX:        true,
		scrollCollapse: true,
		paging:         false,
		fixedColumns:   {
			leftColumns: 0,
			rightColumns: 1
		}
	} );
} );
```

> line 765: need to add if (oOverflow.y) ?

Q2. table with table-bordered may create a unexpected x-scrollbar in the bottom of the fixed colomn.

http://datatables.net/extensions/fixedcolumns/examples/initialisation/right_column.html
and just set rightColumns.

```
$(document).ready(function() {
	var table = $('#example').DataTable( {
		scrollY:        "300px",
		scrollX:        true,
		scrollCollapse: true,
		paging:         false,
		//fixedColumns:   true
		fixedColumns:   {
			leftColumns: 1,
			rightColumns: 1
		}
	} );
} );
```

it seems that either .DTFC_LeftWrapper or .DTFC_RightWrapper have both left & right table-border
> line 695: need to add table's border-right-width ?
> line 696: need to add table's border-left-width ?

Q3: And a question

```
border = $(that.s.dt.nTable).css('border-left-width');
iWidth += typeof border === 'string' ? 1 : parseInt( border, 10 );
```
always read 'border-left-width' (like 5px)  as string ?

Q4: And a question

> line 621: this.s or that.s?
 
thx

**Comment by DataTables** [comment]
I'll try to take a look at this as soon as possible, but there is quite a back log I'm afraid so it might be a little while.

**Comment by cfigueiredo** [comment]
Any updates on this issue? I have the same problem with the latest version os DT and FixedColumns plugin.

**Comment by DataTables** [comment]
No yet - I've been working on other things I'm afraid. Pull requests welcome though :-).

**Comment by DataTables** [comment]
Sorry - I forgot to update this issue when I committed the fix. 228eb5abff37fa0634ef05cc6d801bdad11e42aa addresses it.
