### ISSUE TITLE
IE9+scrollbars : fixed column have large height

### ISSUE THREAD

**Issue by kzmi** [DataTables/FixedColumns#54]
On IE9, the fixed column over the table with horizontal/vertical scrollbars will be displayed with large height.

My sample is: https://jsfiddle.net/kzmi/s4hvgqr6/

The result on IE9:
![ie9](https://cloud.githubusercontent.com/assets/3753969/13802688/9a65340e-eb81-11e5-8dfa-94d6eb9e150d.png)

**Comment by kzmi** [comment]
It seems the issue of DataTables...
Without FixedColumns, wrapper element with scrollbar is also rendered with wrong height on IE9.
I also found that wrapper element grows its height when <a>element in a cell was highlighted.

DataTables set max-height to div.dataTables_scrollBody, but jQuery's outerHeight() returns wrong height for div.dataTables_scrollBody on IE9.

My workaround is here: https://jsfiddle.net/kzmi/zwtxzopn/
I specified 'height' pixels on div.dataTables_scrollBody explicitly, then called fixedColumns().update().

**Comment by DataTables** [comment]
Thanks for flagging this up. I'll take a detailed look before the next release.

**Comment by DataTables** [comment]
Weirdly I can't reproduce this issue I'm afraid. I've just tried your example and also my local ones in IE9 and wasn't able to see the same effect. I'll try again on another Windows machine when I get access to one.

**Comment by ilgiz-badamshin** [comment]
Reproduced:
![ie9](https://cloud.githubusercontent.com/assets/7591988/19867440/e050b852-9fb4-11e6-982c-b2c828682f16.jpg)

extra height is equals to header rows height:
![ie9_2](https://cloud.githubusercontent.com/assets/7591988/19867687/d6aa2daa-9fb5-11e6-8947-bf45d03134f8.png)
Any ideas?

**Comment by DataTables** [comment]
If you could link to a test case showing the issue, that would be great.

**Comment by ilgiz-badamshin** [comment]
I used @kzmi example: https://jsfiddle.net/kzmi/s4hvgqr6/
