### ISSUE TITLE
Fixed columns throws error when destroying a DataTable

### ISSUE THREAD

**Issue by wasbridge** [DataTables/FixedColumns#56]
Line 621 of dataTables.fixedColumns.js should read:

$(that.s.dt.nTableWrapper).off( '.DTFC' );

but it current reads:

$(this.s.dt.nTableWrapper).off( '.DTFC' );

**Comment by DataTables** [comment]
Hi,

That issue was fixed a while ago by c2888c60fb54b1196cf28b5add559d2cb0be71a2.

**Comment by wasbridge** [comment]
Sorry, my mistake.  For some reason bower gave me a version without that
fix.

**Comment by DataTables** [comment]
No problem. The fix hasn't been released yet.
