### ISSUE TITLE
Fixed column scrollbar showing

### ISSUE THREAD

**Issue by tclindner** [DataTables/FixedColumns#59]
When first loading the fixed column example, there is a scrollbar within the column. This behavior seems to be specific to Chrome. In Firefox, there is no horizontal scrollbar, but there is a vertical scrollbar inline with the header at every breakpoint (this also occurs on the combined fixed column/header example in Firefox).

**Chrome**
![image](https://cloud.githubusercontent.com/assets/5178550/17037954/f548eb5a-4f58-11e6-8960-550ff9e74223.png)

**Firefox**
![image](https://cloud.githubusercontent.com/assets/5178550/17037961/037cdd94-4f59-11e6-9a02-614decfb34fb.png)

**Comment by DataTables** [comment]
Can you link to a test page showing the issue please.

**Comment by ro7584** [comment]
Looks like the same issue. I think it probably min-width and border style causing the wrong width calculate in line 652 "_fnColCalc" function.

https://jsfiddle.net/a04ffztd/

**Comment by tclindner** [comment]
Thanks, @ro7584! I lost track of this ticket. I appreciate the help.

**Comment by DataTables** [comment]
Sorry for the massive delay!

The example contains:

```css
table { 
  border-collapse: collapse !important;
}
```

I've found that causes no end of problems with column widths and trying to match them between tables. I'm afraid that as a result that option is not currently supported in DataTable.

If it is possible to recreate this issue without column collapse, I'll do what I can to resolve it. With it removed from the test case it works as expected.

Until then I'll close this issue, but feel free to reopen with a test case.

**Comment by tclindner** [comment]
Thanks @DataTables!
