### ISSUE TITLE
Only the header column is fixed when table contains multiple <tbody> tags

### ISSUE THREAD

**Issue by HenryKeen** [DataTables/FixedColumns#61]
I've got a strange issue with the fixedcolumns plugin in datatables when the table contains multiple <tbody> tags.

When there are multiple tbody tags then only the header column stays fixed.

I'm hoping to have a look at a fix myself and submit a PR (if it doesn't require a whole re-write), but any help would be greatly appreciated.

Forum thread here:
https://datatables.net/forums/discussion/38553/only-the-header-column-is-fixed-when-table-contains-multiple-tags?new=1

**Comment by DataTables** [comment]
> multiple tbody tags

I'm afraid that DataTables currently does not support multiple `tbody` elements. I know that it is valid in the HTML spec, and it is something I very much want to add in future, but it isn't currently supported I'm afraid.
