### ISSUE TITLE
Zero result and still seeing leftWrapper bordered

### ISSUE THREAD

**Issue by ro7584** [DataTables/FixedColumns#62]
Sample page cloning from [example](https://datatables.net/extensions/fixedcolumns/examples/styling/bootstrap.html)

https://jsfiddle.net/shLd0ay8/

![image](https://cloud.githubusercontent.com/assets/4129139/21845813/21b3965e-d82f-11e6-9cf3-2695665101a2.png)

**Comment by DataTables** [comment]
Was this a bug reported before? What you show is what I expected to happen.

**Comment by ro7584** [comment]
I made the raw second table that look like more natural without leftWrapper bordered.
Updated the [jsfiddle](https://jsfiddle.net/shLd0ay8/1/) 

In my own project, I added some statements in dataTables.fixedColumns.js line 1177 in order to determine leftWrapper shown or not.


Finally, I hope this suggestion could be helpful for this project :)

**Comment by DataTables** [comment]
[This `if` statement](https://github.com/DataTables/FixedColumns/blob/f46a1d22aedc6aef29b5de7de21c79c16737284b/js/dataTables.fixedColumns.js#L1228) is what is causing that cell to appear. It was added as others wanted it to appear so there isn't a disconnect between when data is shown and not.

If you don't want it add:

```css
tr.DTFC_NoData {
  visibility: hidden;
}
```

to the CSS and that will do it.
