### ISSUE TITLE
fixedColumns().cellIndex() should not be deprecated

### ISSUE THREAD

**Issue by mpryvkin** [DataTables/FixedColumns#64]
Documentation for [fixedColumns().cellIndex()](https://datatables.net/reference/api/fixedColumns().cellIndex()) mentions that `fixedColumns().cellIndex()` is deprecated and can be replaced with `cell().index()`.

However when `rightColumns` is used, `cell().index()` fails to calculate correct column index when cell from the cloned table is provided as an argument.

See [this example](https://jsfiddle.net/rgkh213h/) for code and demonstration. Click on "Get Index" button and compare column indexes returned by `fixedColumns().cellIndex()` and `cell().index()`.

**Comment by DataTables** [comment]
Completely agree - thanks for flagging this up!

**Comment by DataTables** [comment]
Looks like I've already fixed this on in cb82db5ed0ea5c9af6b97b5ac3712c9c2a4efef5 and had forgotten about it. Its in the nightly version: https://jsfiddle.net/rgkh213h/1/ .
