### ISSUE TITLE
Some callbacks/functions stop delivering properly

### ISSUE THREAD

**Issue by s0By** [DataTables/FixedColumns#65]
I don't know if it is exactly connected to FixedColumns, but since it happens only when activating the extension then I guess it does. 

I have a rowCallback which looks something like:
```
rowCallback: function (row, data, index) {
      var _this = this;
      $(row).click(function (e) {
                var target = $(e.target);
                console.log(target);
                ...
                code
                ...
      });
},
```

And a listener which I start in `initComplete` function:
```
$(table.table().container()).on('change', 'input[type="checkbox"]', function() {
      ...
      code
      ...
});
```

Both by some miracle stop working as soon as I activate fixedColumn extension, I have a regular init on 1 column:
```
fixedColumns:   {
     leftColumns: 1
},
```
Both callbacks work, partially at least, I have some other functions in `initCompelete`, they work, but this listener doesn't, which is weird and is troublesome for me. `rowCallback` does launch as well, I can get row data or whatever I want, but it doesn't reach to `click` event.

**Comment by DataTables** [comment]
Could you ask future support questions in the [forums](//datatables.net/forums) as requested in the new issue template text please?

Could you also link to a test case showing the issue?

**Comment by s0By** [comment]
Should I move the question there or we can resolve it here? Question goes to both of my issues.

**Comment by DataTables** [comment]
That would be great thanks. If you could post a link to the forum discussions in each issue, that would be useful.

**Comment by s0By** [comment]
[Link](https://datatables.net/forums/discussion/41652/fixedcolumns-rowcallback-issue) of the discussion post on forums. Hope you'll be able to help. I didn't mention the `change` event listener in the post, because that was actually the problem in the extra solutions that I'm using. Got that fixed already.

And also looking forward to another answer on my 'Preserving row attributes / proper row reordering' question.

**Comment by DataTables** [comment]
I've added a reply in the forum. I'll try to look at your other thread as soon as I can.
