### ISSUE TITLE
Empty table message rendered just after fixed columns

### ISSUE THREAD

**Issue by mmuruev** [DataTables/FixedColumns#68]
Seems like fixedColumns missing 'no records' datatable message. It rendered just after fixed column. Not sure this is bug or by design. http://screencloud.net/v/pfxDu example.

**Comment by DataTables** [comment]
The Sorry for the delay in getting back to you here. I would expect the fixed columns not to have a message in them, as shown here: http://live.datatables.net/picakege/1/edit .

It looks like it is currently working as intended.

**Comment by gorbeia** [comment]
If you make more columns fixed in that example part of the message will be hidden:
http://live.datatables.net/picakege/2/edit

I have been able to make it visible applying the folwing styling:

```css
table.dataTable.display tbody tr.DTFC_NoData {
  background-color: transparent;
}
```
http://live.datatables.net/picakege/3/edit
