### ISSUE TITLE
horizontal scroll bar on fixed columns

### ISSUE THREAD

**Issue by RohanHart** [DataTables/FixedColumns#7]
A horizontal scroll bar is displayed on the left fixed column because it's being created fractionally too narrow.  Adding overflow-x:hidden to the DTFC_LeftBodyLiner div seems to fix the display issue

**Comment by michaellouviere** [comment]
Any update on this? Experiencing the same problem and setting overflow: hidden doesn't solve for all use cases.

**Comment by DataTables** [comment]
I've just created this test case http://live.datatables.net/qoxunode/1/edit (not sure what is going wrong with the one linked above, which doesn't appear to actually use FixedColumns) and it appears to work as expected in Firefox.

@michaellouviere Can you link to your page so the issue can be debugged please?

**Comment by DataTables** [comment]
Going to close this issue for now. If you are able to post a link with a test case showing the issue, please do so and I'll reopen it.

**Comment by mkurz** [comment]
There is this discussion which looks like it's about the same bug: https://datatables.net/forums/discussion/33008/scrolx-create-scrolbar-under-fixed-columns-on-firefox-with-bootstrap

**Comment by padam10** [comment]
@DataTables  If you copy the url of your test case "http://live.datatables.net/qoxunode/1/edit" and run in IE 11. Have it display 100 records per page, place cursor at the anywhere under the name column and try scrolls up and down. Fixed column and rest of the column move separately.  Cell on a fixed column do not align with the rest of the cells

**Comment by DataTables** [comment]
Thanks - I'll look into it before the next release.

**Comment by tanwanimanisha** [comment]
@DataTables , Do you have any update on this or any timeline to fix this issue?

**Comment by DataTables** [comment]
I haven't had a chance to look into it yet I'm afraid. I will try to do so as soon as I can, but don't have a set timeframe for it.

**Comment by yubo56** [comment]
Also had this problem, used the recommended style to fix it. It does literally seem to be off by one or so, so not a huge deal, just wanted to chime in with another repro

**Comment by thetlwinoojustlogin** [comment]
When scrolling fixed columns dataTables near to bottom, it cann't show alignment properly.  That can be seen in dataTable site https://datatables.net/extensions/fixedcolumns/examples/initialisation/two_columns.html.

**Comment by AllanJard** [comment]
Closing due to the v4 upgrade which significantly simplified FixedColumns through the use of `position sticky`. This removes the need for cloned elements and resolves a ton of issues, including this one.
