### ISSUE TITLE
fixed left column's border has 1px offset to non-fixed columns

### ISSUE THREAD

**Issue by stanleyxu2005** [DataTables/FixedColumns#72]
You can simple reproduce by scrolling the table to the bottom, and then you will see the bottom border of cells in column "Last name" and "Position" have 1px offset. (I'm using Chrome 66)
https://www.datatables.net/extensions/fixedcolumns/examples/styling/colvis.html

![image](https://user-images.githubusercontent.com/5162687/40005399-6a6bded0-57ca-11e8-909f-de01968868fc.png)

**Comment by DataTables** [comment]
I've just been digging into this and I don't think it is actually a border issue - to be honest, I don't actually know what it is yet!

Looking at the Chrome inspector, in my example table I can see that the scrolling tables have exactly the same height (to .33 pixels!). But that doesn't explain the misalignment.

I'm planning a rewrite of how FixedColumns works, so I'm afraid I'm going to leave this one until then.
