### ISSUE TITLE
Footer Values not accessable by id

### ISSUE THREAD

**Issue by finnsea** [DataTables/FixedColumns#73]
Recently, I was trying to manipulate an item in the footer of the scrolling section (not fixed) via the element's id based on an event elsewhere on the page. However, because of the way that the elements are copied to the left/right fixed columns, jQuery was not able to find the correct element due to multiple elements with the same id.

**Comment by DataTables** [comment]
The id's should be getting stripped from the cloned elements. Can you link to a test case showing the issue please.
