### ISSUE TITLE
For rtl tables wrong side is being padded

### ISSUE THREAD

**Issue by all43** [DataTables/FixedColumns#74]
`scrollbarAdjust` function always adds padding on the right side, even for RTL tables where it should be on the left.

Details here:
https://stackoverflow.com/questions/56914256/extra-space-in-header-for-right-to-left-tables-in-html/56915061#56915061

**Comment by DataTables** [comment]
Thank you! I'll get this sorted for the next patch.

**Comment by AllanJard** [comment]
Closing due to the v4 upgrade which significantly simplified FixedColumns through the use of `position sticky`. This removes the need for cloned elements and resolves a ton of issues, I believe including this one.
