### ISSUE TITLE
Fixed columns can be scrolled independently

### ISSUE THREAD

**Issue by frzsombor** [DataTables/FixedColumns#75]
If I start scrolling the datatable with the mouse over a non-fixed column, and slowly, during scrolling I move the mouse over a fixed column (or vice-versa), the fixed and non-fixed columns lose the connection. Please check the GIF below that I recorded on the [official examples page](https://datatables.net/extensions/fixedcolumns/examples/initialisation/left_right_columns.html) (may take a few seconds to load):

![datatables-bug-3](https://user-images.githubusercontent.com/7306657/61124841-57711300-a4a8-11e9-9429-3c294a3e0c56.gif)

**Comment by DataTables** [comment]
Thank you. It looks like you need to be doing a scrolling action while moving between the fixed and non-fixed columns. The software needs to perform different actions depending on where the scrolling starts, and it doesn't handle this switch which is why this problem occurs.

Probably a tricky one to fix this, but I'll look into it for the next release :-).

**Comment by frzsombor** [comment]
Thanks for the quick reply!
Are there any ETA for the next release (even just an approximate)?

**Comment by DataTables** [comment]
Its probably a couple of weeks away, but I can't promise to have this fixed for the next release I'm afraid. I've seen a similar issue before and it wasn't easy to fix, so I suspect this is going to take a fair amount of work to get it sorted out.

**Comment by bezanis** [comment]
I've created a PR to fix this issue: https://github.com/DataTables/FixedColumns/pull/77

**Comment by AllanJard** [comment]
Closing due to the v4 upgrade which significantly simplified FixedColumns through the use of `position sticky`. This removes the need for cloned elements and resolves a ton of issues, including this one.
