### ISSUE TITLE
Datatble Fixed column misaligned in Chrome 78 update

### ISSUE THREAD

**Issue by josongvmtechphp** [DataTables/FixedColumns#78]
After chrome version update to 78, datatable fixed column designs are broken. no design issues in other browsers or older chrome versions. Issue is shown below

![slackoverflowimg](https://user-images.githubusercontent.com/24821465/67929913-8f7d9c80-fbe4-11e9-811e-1d8e4d0dd712.jpg)

issue only comes if the column have lengthy text. or html content

**Comment by colin0117** [comment]
Please see comment on thread: https://datatables.net/forums/discussion/58885/datatble-fixed-column-misaligned-in-chrome-78-update#latest . Let's move the discussion there.
