### ISSUE TITLE
Add support for PHP 7.3

### ISSUE THREAD

**Issue by chrislow** [DataTables/FixedColumns#79]
We need to update the plugin, because it is using the deprecated `strpos()` function.
Right now the following error-message is thrown, when the plugin is installed on the newest wordpress version with PHP 7.3.10.

> Deprecated: strpos(): Non-string needles will be interpreted as strings in the future. 
> Use an explicit chr() call to preserve the current behavior in 
> wp-content/plugins/tablepress-datatables-fixedcolumns/libraries/plugin-update-checker.php on line 851

https://www.php.net/manual/en/function.strpos.php

I can open a pull request if you want.

**Comment by DataTables** [comment]
Can you clarify where that code is please? This repo doesn't contain any PHP...
