### ISSUE TITLE
Rounded heights create gaps

### ISSUE THREAD

**Issue by beam2web** [DataTables/FixedColumns#81]
When using https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/offsetHeight in your JS, the heights for each tr would be rounded to an integer, see the documentation:

"This property will round the value to an integer. If you need a fractional value, use element.getBoundingClientRect()."

The calculated inline height is 66px But the original calculation of my Firefox is 66.2833px
<img width="1222" src="https://user-images.githubusercontent.com/8706639/88287692-ec7d2d80-ccf2-11ea-9dbf-5350bdca0e9a.png">

It can happen that there are columns in the original table that are slightly higher than the calculation in the copied columns (table columns take the place that they need), and then the rows no longer match exactly. (on the left the normal table and on the right the sticky column) all TRs have inline height=66px; but some <tr> are a bit higher than in the screen before -> So with many rows you can see the difference better
<img width="200" alt="Bildschirmfoto 2020-07-23 um 14 40 04" src="https://user-images.githubusercontent.com/8706639/88287781-146c9100-ccf3-11ea-936a-de4a87d4d2da.png">

**Comment by AllanJard** [comment]
Closing due to the v4 upgrade which significantly simplified FixedColumns through the use of `position sticky`. This removes the need for cloned elements and resolves a ton of issues, including this one.
