### ISSUE TITLE
Column Filter values are lost when Fixed Column and Scroll Resize executes relayout()

### ISSUE THREAD

**Issue by bailinhuang-mw** [DataTables/FixedColumns#83]
When ScrollResize is applied to the table, the values on the input tags in the Column Filters disappear after a search and redraw.

Is there any progress with this [issue breaking with Column Filters and Scroll Resize](https://datatables.net/forums/discussion/59947)?

**Comment by AllanJard** [comment]
Closing due to the v4 upgrade which significantly simplified FixedColumns through the use of `position sticky`. This removes the need for cloned elements and resolves a ton of issues, including this one.
