### ISSUE TITLE
Bootstrap dropdown display issue in the fixed column

### ISSUE THREAD

**Issue by jack-gaojz** [DataTables/FixedColumns#84]
Jquery DataTable Version: 3.3.2
Bootstrap Version: 4.5
The Screenshot as below:
![QQ截图20210326080708](https://user-images.githubusercontent.com/74571567/112558855-b0164a00-8e0a-11eb-86f5-c6a081e7204b.png)

**Comment by DataTables** [comment]
Can you link to a test case showing the issue please.

**Comment by events-jonas-chrisw** [comment]
i've got the same problem. the dropdown doesn't seem to like "position:sticky"

**Comment by AllanJard** [comment]
I'm happy to take a look at a test case showing the issue as I noted above.

**Comment by events-jonas-chrisw** [comment]
I found a similar issue with a jsfiddle here:

https://stackoverflow.com/questions/70110234/bootstrap4-dropdown-inside-sticky-table-cells

https://jsfiddle.net/m0gnak27/

its not directly related to Fixedcolumns but is a result of using dropdowns in a sticky column

**Comment by AllanJard** [comment]
Its a stacking error, and unfortunately not one solved with a simple z-index. You'd need to have the attach point of the dropdown be the table container or the document body, rather than adjacent to the button.

**Comment by events-jonas-chrisw** [comment]
> Its a stacking error, and unfortunately not one solved with a simple z-index. You'd need to have the attach point of the dropdown be the table container or the document body, rather than adjacent to the button.

I thought as much :-) thanks anyway

**Comment by AllanJard** [comment]
Closing due to the v4 upgrade which significantly simplified FixedColumns through the use of `position sticky`. This removes the need for cloned elements and resolves a ton of issues, including this one.
