### ISSUE TITLE
Something wrong with latest release 4.0.0

### ISSUE THREAD

**Issue by msxavi** [DataTables/FixedColumns#86]
Hey all,

Our CI has raised the following this morning:

```
Sprockets::FileNotFound: couldn't find file 'datatables-fixed-columns/js/dataTables.fixedColumns.js' with type 'application/javascript'
--
```

Since the bower definition we have is version agnostic: `"datatables-fixed-columns": "git@github.com:DataTables/FixedColumns.git"`

As a workaround: `git@github.com:DataTables/FixedColumns.git#3.3.3` compiles successfully. 

Thank you!

**Comment by AllanJard** [comment]
Hi - thanks for your message. Could you switch to using the `datatables.net-fixedcolumns` package please? The `datatables.net*` packages are our distributions ones, this is just a source repo.

The [download builder](https://datatables.net/download/) can help make sure you get the right packages.

**Comment by msxavi** [comment]
@AllanJard ah. Thanks. That should be it.
