### ISSUE TITLE
NULL-reference exception if table node is removed after destroy()

### ISSUE THREAD

**Issue by morkai** [DataTables/FixedColumns#87]
Reproduction: https://jsfiddle.net/zd4mvnjL/
1. Create a table.
2. Call `DataTable.destroy()`.
3. Remove the table from the document.
4. `Uncaught TypeError: Cannot read properties of undefined (reading 'offsetWidth')`

Calling `DataTable.destroy()` without `true` makes all columns visible. FixedColumns listens for `column-visibility` event, which when triggered, creates a 50ms timer to recalculate column styles (one timer for each column - shouldn't it be debounced?). The `FixedColumns._addStyles()` function references the table node which results in an error if it was removed from the DOM before the 50ms passed.

https://github.com/DataTables/FixedColumns/blob/c29674b122f53a6dceb8c2e4745970ea1d540f86/src/FixedColumns.ts#L201

`scroll` is undefined in this case.

**Comment by AllanJard** [comment]
Thank you for flagging this up. Fixed [in the FixedColumns repo](https://github.com/DataTables/FixedColumns/commit/7ca01c7ae8e0dde467c7e231b690018460265527).
