### ISSUE TITLE
DataTable 1.11.3+FixedColumns 4.0.1 issue:fixedColumns(...).relayout is not a function

### ISSUE THREAD

**Issue by alexwenbj** [DataTables/FixedColumns#88]
I use the 2 latest releases:
https://cdn.datatables.net/1.11.3/js/jquery.dataTables.min.js
https://cdn.datatables.net/fixedcolumns/4.0.1/js/dataTables.fixedColumns.min.js
and get the following error:
fixedColumns(...).relayout is not a function

It is OK to use the 2 older releases here:[http://live.datatables.net/duqocaka/1/edit](http://live.datatables.net/duqocaka/1/edit)

I checked the fixedColumns 4.0.1 code in CDN,can't find the relayout() function,but it can be found in 3.2.6.

**Comment by AllanJard** [comment]
There shouldn't be any need for it with v4, thus it was removed. Are you finding that it is needed for some reason?

**Comment by alexwenbj** [comment]
In my case, sometimes the fixed thead>tr>td not align the tbody>tr>td:
<img width="517" alt="snap" src="https://user-images.githubusercontent.com/12047524/147231561-5ed85130-0c91-483a-9dc6-2917342ab41b.png">

**Comment by alexwenbj** [comment]
Cause it is not an issue for the new version, it is for the usage, I close it.

**Comment by alexwenbj** [comment]
@AllanJard It seems this version fixedColumns is compatible with the rowGroup?

**Comment by AllanJard** [comment]
No sorry, Our [compatibility chart is here](https://datatables.net/download/compatibility). The FixedColumns don't operate with the colspan-ing grouping rows that RowGroups adds.
